apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      name: client-frontend
  template:
    metadata:
      labels:
        app: frontend
        type: frontend-pod
        name: client-frontend
    spec:
      containers:
      - name: frontend
        image: ibraheem15/client:frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80