apiVersion: v1
kind: Service
metadata:
  name: classroom-1174-backend-service # Name of the service
spec:
  type: ClusterIP
  selector:
    app: scd-final # Selects the pods with the label 'app: episode-1'
    type: backend-classroom-pod # Selects the pods with the label 'type: backend'
  ports:
    - protocol: TCP
      port: 3175 # Port that the service will listen on
      targetPort: 3175 # Port on the pod that the service will forward traffic to
