apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-1174-backend-deployment
  labels:
    app: scd-final
  annotations:
    description: "Post backend service for SCD final project"
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scd-final
      name: post-1174-backend
  template:
    metadata:
      name: post-1174-backend
      labels:
        app: scd-final
        type: backend-post-pod
        name: post-1174-backend
    spec:
      containers:
        - name: myapp-1174
          image: bi1alakbar/scd-final-backend-post:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3176
          env:
            - name: MONGO_URL
              value: mongodb://backend-1174-db-service:80/A3?directConnection=true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          livenessProbe:
            tcpSocket:
              port: 3176
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3176
            initialDelaySeconds: 10
            periodSeconds: 5
