apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-1174-backend-deployment
  labels:
    app: scd-final
  annotations:
    description: "Backend authentication service for SCD final project"
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scd-final
      name: auth-1174-backend
  template:
    metadata:
      name: auth-1174-backend
      labels:
        app: scd-final
        type: backend-auth-pod
        name: auth-1174-backend
    spec:
      containers:
        - name: myapp-1174
          image: bi1alakbar/scd-final-backend-auth:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3174
          env:
            - name: MONGO_URL
              value: mongodb://backend-1174-db-service:80/A3?directConnection=true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          # Bilal Akbar 21i-1174
          livenessProbe:
            httpGet:
              path: /health
              port: 3174
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 3174
            initialDelaySeconds: 5
            periodSeconds: 10
