apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-1174-db-deployment
  labels:
    app: scd-final
  annotations:
    description: "Database service for SCD final project"
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scd-final
      name: backend-db
  template:
    metadata:
      name: backend-db
      labels:
        app: scd-final
        type: db-pod
        name: backend-db
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.6
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
