apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-1174-deployment
  labels:
    app: scd-final
  annotations:
    description: "Frontend service for SCD final project"
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scd-final
      name: frontend-1174
  template:
    metadata:
      name: frontend-1174
      labels:
        app: scd-final
        type: frontend-pod
        name: frontend-1174
    spec:
      containers:
        - name: myapp-1174
          image: bi1alakbar/scd-final-frontend:1
          imagePullPolicy: Always
          ports:
            - containerPort: 1174
          env:
            - name: REACT_APP_AUTH_URL
              value: http://auth-backend-service:3174
            - name: REACT_APP_CR_URL
              value: http://classroom-backend-service:3175
            - name: REACT_APP_POST_URL
              value: http://post-backend-service:3176
            - name: REACT_APP_EVENTBUS_URL
              value: http://eventbus-backend-service:3180
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 1174
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 1174
            initialDelaySeconds: 30
            periodSeconds: 5
